interface=eth1
bind-interfaces
port=0

enable-ra
dhcp-range=::,constructor:eth1,ra-stateless,ra-names,12h

dhcp-option=option6:dns-server,[2001:db8:0:f102::1]

ra-param=eth1,3,30

dhcp-option=option6:26,1492
