
#interface eth1
#{
#    AdvSendAdvert on;
#    prefix 2804:4d38:4000:6079::/64
#    {
#        AdvOnLink on;
#        AdvAutonomous on;
#    };
#};

#por enquanto usar IP de documentacao
#interface eth1
#{
#        AdvSendAdvert on;
#        prefix 2001:db8:0:f101::/64
#        {
#                AdvOnLink on;
#                AdvAutonomous on;
#        };
#};

#interface eth1 {
#    AdvSendAdvert on;
#    MinRtrAdvInterval 3;
#    MaxRtrAdvInterval 10;
#    prefix 2804:4d38:4000:351d::/64 {
#        AdvOnLink on;
#        AdvAutonomous on;
#        AdvRouterAddr on;
#    };
#};
#interface eth1 {
#    AdvSendAdvert on;
#    AdvDefaultLifetime 7200;
#    MinRtrAdvInterval 3;
#    MaxRtrAdvInterval 30;
#    prefix 2804:4d38:8019:c300::/64 {
#        AdvOnLink on;
#        AdvAutonomous on;
#    };
#    RDNSS 2001:db8:0:f102::1 {
#        AdvRDNSSLifetime 7200;
#    };
# AdvLinkMTU 1492;
#};
interface eth1 {
    AdvSendAdvert on;
    AdvDefaultLifetime 7200;
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 30;
    AdvLinkMTU 1492;

    prefix ::/64 {
        AdvOnLink on;
        AdvAutonomous on;
        Base6Interface eth1;   # pega o prefixo da própria eth1
    };

    RDNSS 2001:db8:0:f102::1 {
        AdvRDNSSLifetime 7200;
    };
};
